# Generated by Django 3.1 on 2020-08-27 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('Roast', 'Roast'), ('Boast', 'Boast')], max_length=20)),
                ('votes', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=150)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
