# Generated by Django 3.1 on 2020-08-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='votes',
            field=models.IntegerField(),
        ),
    ]
