# Generated by Django 3.1 on 2020-08-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_app', '0003_postmodel_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='post_time',
        ),
    ]
