# Generated by Django 3.1 on 2020-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_app', '0004_remove_postmodel_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='votes',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
